name: "Build and test"
on:
  workflow_dispatch:
  push:
  pull_request:

env:
  RADIO_TOOL_VERSION: 0.2.2

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: install-deps
        run: |
          sudo apt update
          sudo apt install -y git pkg-config build-essential meson libsdl2-dev libreadline-dev dfu-util cmake libusb-1.0-0 libusb-1.0-0-dev libcodec2-dev codec2
      - name: setup meson
        run: meson setup build_linux
      - name: Compile linux
        run: |
          meson compile -C build_linux openrtx_linux
          meson compile -C build_linux openrtx_linux_smallscreen
          meson compile -C build_linux openrtx_linux_mod17
      - uses: actions/upload-artifact@v4
        with:
          name: linux_build
          path: |
            build_linux/openrtx_linux
            build_linux/openrtx_linux_smallscreen
            build_linux/openrtx_linux_mod17

  build-arm:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: install-deps
        run: |
          sudo apt update
          sudo apt install -y git pkg-config build-essential meson libsdl2-dev libreadline-dev dfu-util cmake libusb-1.0-0 libusb-1.0-0-dev libcodec2-dev codec2
      - name: install miosix
        run: |
          wget https://miosix.org/toolchain/MiosixToolchainInstaller.run
          chmod +x MiosixToolchainInstaller.run
          sudo sh MiosixToolchainInstaller.run
      - name: setup meson
        run: meson setup --cross-file cross_arm.txt build_arm
      - name: Compile arm targets
        run: |
          meson compile -C build_arm openrtx_md3x0_wrap
          meson compile -C build_arm openrtx_mduv3x0_wrap
          meson compile -C build_arm openrtx_md9600_wrap
          meson compile -C build_arm openrtx_gd77_wrap
          meson compile -C build_arm openrtx_dm1801_wrap
          meson compile -C build_arm openrtx_mod17_wrap
      - uses: actions/upload-artifact@v4
        with:
          name: arm_build
          path: build_arm/openrtx_*_wrap


  unit-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: install-deps
        run: |
          sudo apt update
          sudo apt install -y git pkg-config build-essential meson libsdl2-dev libreadline-dev dfu-util cmake libusb-1.0-0 libusb-1.0-0-dev libcodec2-dev codec2
      - name: setup meson
        run: meson setup build
      - name: run unit test
        run: meson test -C build
